# Generated by Django 4.1.5 on 2023-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0002_alter_productcategory_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(db_index=True, null=True, verbose_name='Main description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(db_index=True, null=True, verbose_name='Main description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(db_index=True, max_length=360, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(db_index=True, max_length=360, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='Title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='Title_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Title'),
        ),
    ]
