# Generated by Django 4.1.5 on 2023-04-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0006_alter_product_image_alter_product_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Last_Update_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 22, 29, 30, 282015), verbose_name='Last_Update_Time'),
        ),
    ]
