# Generated by Django 4.1.5 on 2023-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteSetting_Module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, verbose_name='Title')),
                ('Title_fa', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('Title_en', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('ShortDescription', models.CharField(max_length=50, verbose_name='Short Description')),
                ('ShortDescription_fa', models.CharField(max_length=50, null=True, verbose_name='Short Description')),
                ('ShortDescription_en', models.CharField(max_length=50, null=True, verbose_name='Short Description')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Description_fa', models.TextField(null=True, verbose_name='Description')),
                ('Description_en', models.TextField(null=True, verbose_name='Description')),
                ('Image', models.ImageField(upload_to='images/Teams', verbose_name='اواتار ')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, verbose_name='Title')),
                ('Title_fa', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('Title_en', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('ShortDescription', models.CharField(max_length=50, verbose_name='Short Description')),
                ('ShortDescription_fa', models.CharField(max_length=50, null=True, verbose_name='Short Description')),
                ('ShortDescription_en', models.CharField(max_length=50, null=True, verbose_name='Short Description')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Description_fa', models.TextField(null=True, verbose_name='Description')),
                ('Description_en', models.TextField(null=True, verbose_name='Description')),
                ('Create_Date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('Create_Date_fa', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Date')),
                ('Create_Date_en', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Date')),
                ('slider', models.ManyToManyField(to='SiteSetting_Module.slider', verbose_name='Slider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
