# Generated by Django 4.1.5 on 2023-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('full_name', models.CharField(max_length=300, verbose_name='full_name')),
                ('message', models.TextField(verbose_name='message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='is_read_by_admin')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us list',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
