# Generated by Django 4.1.5 on 2023-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting_Module', '0003_navbar_salesproducts_en_navbar_salesproducts_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='SalesProducts',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SalesProducts'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='SalesProducts_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SalesProducts'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='SalesProducts_fa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SalesProducts'),
        ),
    ]
