# Generated by Django 4.1.5 on 2023-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting_Module', '0004_alter_navbar_salesproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Price',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='Price_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='Price_fa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Price'),
        ),
    ]
